# Generated by Django 5.2.6 on 2025-10-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_fix_missing_cols'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumers',
            name='kvah_Status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consumers',
            name='kvah_manual',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
